dist			src/azerothcore-wotlk/env/dist
data			src/azerothcore-wotlk/env/dist/data
data/mmaps-config.yaml	../bin/mmaps-config.yaml
data/map_extractor	../bin/map_extractor
data/mmaps_generator	../bin/mmaps_generator
data/vmap4_assembler	../bin/vmap4_assembler
data/vmap4_extractor	../bin/vmap4_extractor
