src/azerothcore-wotlk						git@github.com:mod-playerbots/azerothcore-wotlk.git
src/azerothcore-wotlk/modules/mod-playerbots			git@github.com:mod-playerbots/mod-playerbots.git
src/azerothcore-wotlk/modules/mod-aoe-loot			git@github.com:azerothcore/mod-aoe-loot.git
src/azerothcore-wotlk/modules/mod-no-hearthstone-cooldown	git@github.com:BytesGalore/mod-no-hearthstone-cooldown.git
src/azerothcore-rudb						git@github.com:SergeyBliznec/azerothcore-rudb.git
